"""
finetune_mammo_SR.py
====================
Stage 2 Finetuning for mammography super-resolution.

Starting Point : A .keras model pre-trained on DIV2K (Stage 2 from TrainSR_GPU.py)
Target Domain  : Mammography images (mammo-bench)
Train Directory: DATASET/mammo_train/   (generated by 1_select_mammo_images.py)
Val Directory  : DATASET/mammo_val/

LR Degradation — Med-BSR (Shao et al. 2023) + 6 MST methods:
  BLUR  : Isotropic (B_iso) or anisotropic (B_aniso) Gaussian — randomized per patch.
  NOISE : Additive Gaussian (grayscale / per-channel / generalized, prob 2/5, 2/5, 1/5).
  DOWN  : 6 MST methods (Nearest · Bilinear · Bicubic · Lanczos · Box · Hamming).
  ORDER : Random combination of the 3 steps (random select/combine strategy).

  - TRAIN : Fully randomized parameters and execution order per patch (via tf.py_function).
  - VAL   : Deterministic round-robin across the 6 MST methods (fixed blur→noise→down order)
            → ensures uniform coverage and perfect reproducibility across epochs.

Usage:
  python finetune_mammo_SR.py \\
      --model_path outputs4x/.../stage2_p128_best.keras \\
      --scale 4 --grayscale
"""

import argparse
import csv
import datetime
import gc
import json
import os
import time
from pathlib import Path

import numpy as np
import tensorflow as tf
from mammo_degradation import make_degradation_fn

# Standard Keras aliases for clarity
keras = tf.keras
layers = tf.keras.layers
AUTOTUNE = tf.data.AUTOTUNE
ALLOWED_EXTS = (".png", ".jpg", ".jpeg", ".bmp", ".webp")

# MST Constants matching mammo_degradation
MST_NAMES = ["nearest", "bilinear", "bicubic", "lanczos", "box", "hamming"]
N_MST = len(MST_NAMES)


def parse_args() -> argparse.Namespace:
    """Parses command line arguments for the finetuning pipeline."""
    p = argparse.ArgumentParser(description="Finetune DIV2K SR model on Mammographies")
    p.add_argument("--model_path", type=str, required=True,
                   help="Path to pre-trained .keras model or a folder containing multiple models")
    p.add_argument("--train_csv", type=str, default="DATASET/mammo_train.csv")
    p.add_argument("--val_csv", type=str, default="DATASET/mammo_val.csv")
    p.add_argument("--out_root", type=str, default="FINETUNE_RESULTS")
    
    p.add_argument("--scale", type=int, default=4, help="Upscaling factor (2 or 4)")
    p.add_argument("--patch_size", type=int, default=128, help="HR patch size during training")
    p.add_argument("--batch_size", type=int, default=8)
    p.add_argument("--lr", type=float, default=2e-5, help="Finetuning learning rate")
    p.add_argument("--max_epochs", type=int, default=50)
    p.add_argument("--es_patience", type=int, default=8, help="Early stopping patience")
    p.add_argument("--es_min_delta", type=float, default=0.01, help="Minimum delta for PSNR improvement")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--cosine_lr", action="store_true", help="Use Cosine Decay learning rate scheduler")
    p.add_argument("--cpu_mode", action="store_true", help="Force execution on CPU")
    return p.parse_args()


def configure_runtime(cpu_mode: bool = False) -> None:
    """Configures hardware execution parameters and mixed precision policy."""
    print(f"\n[RUNTIME] Configuring hardware (cpu_mode={cpu_mode})...")
    if cpu_mode:
        os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
        tf.config.set_visible_devices([], "GPU")
        print("  -> Forced CPU mode execution.")
    else:
        gpus = tf.config.list_physical_devices("GPU")
        if gpus:
            try:
                for gpu in gpus:
                    tf.config.experimental.set_memory_growth(gpu, True)
                print(f"  -> Found {len(gpus)} GPU(s). Memory growth activated.")
            except RuntimeError as e:
                print(f"  -> GPU config error: {e}")
        else:
            print("  -> No GPUs found. Falling back to CPU.")

    # Apply Mixed Precision policy to accelerate GPU computing
    try:
        policy = tf.keras.mixed_precision.Policy("mixed_float16")
        tf.keras.mixed_precision.set_global_policy(policy)
        print(f"  -> Mixed precision set to: {policy.name}")
    except Exception as e:
        print(f"  -> Mixed precision setup failed: {e}")


# =============================================================================
# Data Pipeline via tf.data
# =============================================================================

def load_csv_paths(csv_path: str) -> list[str]:
    """Loads valid file paths from a metadata CSV."""
    if not os.path.isfile(csv_path):
        raise FileNotFoundError(f"Dataset CSV not found: {csv_path}")
    paths = []
    with open(csv_path, mode="utf-8", errors="ignore") as f:
        reader = csv.DictReader(f)
        for row in reader:
            p = row.get("full_path", "").strip()
            if p and os.path.isfile(p) and p.lower().endswith(ALLOWED_EXTS):
                paths.append(p)
    return paths


def make_finetune_dataset(
    csv_path: str,
    scale: int,
    patch_size: int,
    batch_size: int,
    is_training: bool = True,
    seed: int = 42,
) -> tuple[tf.data.Dataset, int]:
    """
    Creates an optimized pipeline supporting Med-BSR degradation.
    
    - Train: Randomizes downsampling methods internally per patch via a random seed.
    - Val: Applies a stable round-robin sequence to ensure consistent validation.
    """
    file_paths = load_csv_paths(csv_path)
    n_images = len(file_paths)
    if n_images == 0:
        raise ValueError(f"No valid image files found in: {csv_path}")

    ds = tf.data.Dataset.from_tensor_slices(file_paths)
    if is_training:
        ds = ds.shuffle(buffer_size=max(200, n_images), seed=seed, reshuffle_each_iteration=True)

    # 1) Image decoding stage
    def _read_and_decode(path_tensor):
        img_bytes = tf.io.read_file(path_tensor)
        img = tf.image.decode_image(img_bytes, channels=3, expand_animations=False)
        img = tf.image.convert_image_dtype(img, tf.float32)  # Automatically normalizes to [0, 1]
        return img

    ds = ds.map(_read_and_decode, num_parallel_calls=AUTOTUNE)

    # 2) Safe patch cropping stage
    def _extract_crop(img):
        shape = tf.shape(img)
        h, w = shape[0], shape[1]
        target_h = tf.maximum(h, patch_size + 2)
        target_w = tf.maximum(w, patch_size + 2)
        padded = tf.image.resize_with_crop_or_pad(img, target_h, target_w)
        
        if is_training:
            patch = tf.image.random_crop(padded, [patch_size, patch_size, 3], seed=seed)
            patch = tf.image.random_flip_left_right(patch, seed=seed)
            patch = tf.image.random_flip_up_down(patch, seed=seed)
        else:
            patch = tf.image.resize_with_crop_or_pad(padded, patch_size, patch_size)
        return patch

    ds = ds.map(_extract_crop, num_parallel_calls=AUTOTUNE)

    # 3) Degradation function factory integration
    deg_fn = make_degradation_fn(scale=scale, seed=seed)
    lr_size = patch_size // scale

    if is_training:
        def _apply_train_deg(hr_patch):
            # Dynamic downsampling method (-1 flags fully randomized degradation parameters)
            method_seed = tf.random.uniform([], minval=-1, maxval=N_MST, dtype=tf.int32)
            
            def _py_wrapper(hr_t, method_t):
                return deg_fn(hr_t.numpy(), int(method_t.numpy()))
            
            lr_patch = tf.py_function(_py_wrapper, [hr_patch, method_seed], tf.float32)
            lr_patch.set_shape([lr_size, lr_size, 3])
            return lr_patch, hr_patch

        ds = ds.map(_apply_train_deg, num_parallel_calls=AUTOTUNE)
    else:
        # Validation setup: Round-Robin distribution strategy over the 6 MST filters
        indices = list(range(n_images))
        idx_ds = tf.data.Dataset.from_tensor_slices(indices)
        
        zipped_ds = tf.data.Dataset.zip((ds, idx_ds))

        def _apply_val_deg(hr_patch, idx_tensor):
            method_idx = idx_tensor % N_MST  # Cyclic distribution (0, 1, 2, 3, 4, 5, 0, ...)
            
            def _py_wrapper(hr_t, method_t):
                return deg_fn(hr_t.numpy(), int(method_t.numpy()))
            
            lr_patch = tf.py_function(_py_wrapper, [hr_patch, method_idx], tf.float32)
            lr_patch.set_shape([lr_size, lr_size, 3])
            return lr_patch, hr_patch

        ds = zipped_ds.map(_apply_val_deg, num_parallel_calls=AUTOTUNE)

    ds = ds.batch(batch_size).prefetch(buffer_size=AUTOTUNE)
    return ds, n_images


# =============================================================================
# Custom Metrics and Logging Callbacks
# =============================================================================

@tf.keras.utils.register_keras_serializable(package="sr")
def psnr_metric(y_true: tf.Tensor, y_pred: tf.Tensor) -> tf.Tensor:
    """Computes peak signal-to-noise ratio over localized batches."""
    return tf.image.psnr(y_true, y_pred, max_val=1.0)


class CustomProgressLogger(keras.callbacks.Callback):
    """Logs clean epoch breakdowns to the terminal console."""
    def __init__(self, total_epochs: int):
        super().__init__()
        self.total_epochs = total_epochs

    def on_epoch_end(self, epoch: int, logs: dict | None = None) -> None:
        logs = logs or {}
        loss = logs.get("loss", np.nan)
        psnr = logs.get("psnr_metric", np.nan)
        val_loss = logs.get("val_loss", np.nan)
        val_psnr = logs.get("val_psnr_metric", np.nan)
        print(
            f"    Epoch {epoch + 1:02d}/{self.total_epochs:02d} -> "
            f"Loss: {loss:.5f} | PSNR: {psnr:.2f} dB || "
            f"Val Loss: {val_loss:.5f} | Val PSNR: {val_psnr:.2f} dB"
        )


# =============================================================================
# Core Finetuning Engine for a Single Model
# =============================================================================

def finetune_one(
    model_path: str,
    train_ds: tf.data.Dataset,
    val_ds: tf.data.Dataset,
    train_steps: int,
    val_steps: int,
    out_dir: str,
    model_name: str,
    lr: float,
    max_epochs: int,
    es_patience: int,
    es_min_delta: float,
    strategy: tf.distribute.Strategy,
    use_cosine_lr: bool = False,
) -> tuple[float, str, str]:
    """
    Runs the finetuning loop for a given model.
    
    Returns:
        tuple: (best_val_psnr, path_to_best_saved_model, parameters_summary_string)
    """
    # Safeguard to prevent layer naming collision crashes across loop iterations
    keras.backend.clear_session()
    gc.collect()

    # Initialize execution environment context
    with strategy.scope():
        # Custom layer registry tracking references required for load reconstruction
        from TrainSR_GPU import PixelShuffle
        try:
            model = keras.models.load_model(
                model_path,
                custom_objects={"PixelShuffle": PixelShuffle, "psnr_metric": psnr_metric},
                compile=False
            )
            print(f"  -> Model successfully loaded into memory scope.")
        except Exception as e:
            print(f"  -> Critical load error on {model_path}: {e}")
            return 0.0, "ERROR", str(e)

        # Dynamic Learning Rate adjustments
        if use_cosine_lr:
            lr_schedule = keras.optimizers.schedules.CosineDecay(
                initial_learning_rate=lr,
                decay_steps=max_epochs * train_steps,
                alpha=0.01
            )
            opt = keras.optimizers.Adam(learning_rate=lr_schedule)
            lr_desc = f"CosineDecay(init={lr})"
        else:
            opt = keras.optimizers.Adam(learning_rate=lr)
            lr_desc = f"Constant({lr})"

        model.compile(optimizer=opt, loss="mae", metrics=[psnr_metric])

    best_model_path = os.path.join(out_dir, f"ft_{model_name}_best.keras")

    callbacks = [
        keras.callbacks.ModelCheckpoint(
            best_model_path,
            monitor="val_psnr_metric",
            mode="max",
            save_best_only=True,
            verbose=0
        ),
        keras.callbacks.EarlyStopping(
            monitor="val_psnr_metric",
            mode="max",
            patience=es_patience,
            min_delta=es_min_delta,
            restore_best_weights=True,
            verbose=1
        ),
        CustomProgressLogger(total_epochs=max_epochs)
    ]

    print(f"  -> Training updates configured. Steps per epoch: {train_steps} | Steps Val: {val_steps}")
    start_t = time.time()
    
    history = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=max_epochs,
        steps_per_epoch=train_steps,
        validation_steps=val_steps,
        callbacks=callbacks,
        verbose=0
    )
    
    elapsed = time.time() - start_t
    psnr_hist = history.history.get("val_psnr_metric", [0.0])
    best_val_psnr = float(np.nanmax(psnr_hist) if not np.all(np.isnan(psnr_hist)) else 0.0)
    
    print(f"  -> Execution complete in {elapsed/60:.2f} mins. Peak Val PSNR: {best_val_psnr:.3f} dB")

    params_summary = {
        "lr_strategy": lr_desc,
        "base_lr": lr,
        "max_epochs": max_epochs,
        "actual_epochs": len(psnr_hist),
        "runtime_sec": round(elapsed, 2)
    }

    return best_val_psnr, best_model_path, json.dumps(params_summary)


# =============================================================================
# Main Orchestrator Execution Flow
# =============================================================================

def main() -> None:
    args = parse_args()
    configure_runtime(cpu_mode=args.cpu_mode)

    # Generate timestamped logging results path
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    root = os.path.join(args.out_root, f"ft_run_{timestamp}")
    os.makedirs(root, exist_ok=True)

    print(f"\n{'='*75}")
    print(" DOMAIN FINETUNING PIPELINE — MAMMO SUPER-RESOLUTION")
    print(f"{'='*75}")
    print(f"  Model input target : {args.model_path}")
    print(f"  Train CSV source   : {args.train_csv}")
    print(f"  Val CSV source     : {args.val_csv}")
    print(f"  Output directory   : {root}")
    print(f"  Configuration      : Scale=×{args.scale} | Patch={args.patch_size} | Batch={args.batch_size}")
    print(f"  Hyperparameters    : LR={args.lr} | Epochs={args.max_epochs} | Cosine={args.cosine_lr}")
    print(f"='*75\n")

    # ── Discover Candidate Input Models ──────────────────────────────────────
    models_to_run = []
    if os.path.isdir(args.model_path):
        print(f"[SEARCH] scanning directory for models: {args.model_path}")
        for file in sorted(os.listdir(args.model_path)):
            if file.endswith(".keras"):
                full_p = os.path.join(args.model_path, file)
                name = Path(file).stem
                models_to_run.append((name, full_p))
    elif os.path.isfile(args.model_path):
        name = Path(args.model_path).stem
        models_to_run.append((name, args.model_path))
    else:
        raise FileNotFoundError(f"Target path option invalid or missing: {args.model_path}")

    if not models_to_run:
        print("  -> WARNING: No valid .keras files discovered. System exiting.")
        return
    print(f"  -> Discovered {len(models_to_run)} model candidate profiles ready for training.")

    # ── Initialize decoupled data streams ────────────────────────────────────
    print("\n[DATA] Loading and parsing target datasets...")
    train_ds, n_train = make_finetune_dataset(
        args.train_csv, args.scale, args.patch_size, args.batch_size, is_training=True, seed=args.seed
    )
    val_ds, n_val = make_finetune_dataset(
        args.val_csv, args.scale, args.patch_size, args.batch_size, is_training=False, seed=args.seed
    )

    train_steps = int(np.ceil(n_train / args.batch_size))
    val_steps = int(np.ceil(n_val / args.batch_size))
    print(f"  -> Datasets loaded. Train samples: {n_train} | Val samples: {n_val}")

    # Set up distributed GPU compute strategy
    strategy = tf.distribute.get_strategy()  # Default system single-scope mapping fallback

    # Prepare master search report summary tracking file
    summary_path = os.path.join(root, "finetune_summary.csv")
    fieldnames = ["model_name", "source_model", "params", "best_val_psnr", "saved_full_path"]
    with open(summary_path, "w", newline="", encoding="utf-8") as f:
        csv.DictWriter(f, fieldnames=fieldnames).writeheader()

    # ── Finetuning Loop ──────────────────────────────────────────────────────
    for model_name, model_path in models_to_run:
        print(f"\n{'='*60}")
        print(f" FINETUNING: {model_name}")
        print(f"  Source Path: {model_path}")
        print(f"{'='*60}")

        best_psnr, ft_model_path, params = finetune_one(
            model_path=model_path,
            train_ds=train_ds,
            val_ds=val_ds,
            train_steps=train_steps,
            val_steps=val_steps,
            out_dir=root,
            model_name=model_name,
            lr=args.lr,
            max_epochs=args.max_epochs,
            es_patience=args.es_patience,
            es_min_delta=args.es_min_delta,
            strategy=strategy,
            use_cosine_lr=args.cosine_lr,
        )

        # Append performance metrics to the global master CSV sheet
        with open(summary_path, "a", newline="", encoding="utf-8") as f:
            csv.DictWriter(f, fieldnames=fieldnames).writerow({
                "model_name": model_name,
                "source_model": model_path,
                "params": params,
                "best_val_psnr": best_psnr,
                "saved_full_path": os.path.abspath(ft_model_path),
            })

    print(f"\n{'='*75}")
    print(" FINETUNING PROCESS COMPLETED SUCCESSFULLY")
    print(f"  Master Report spreadsheet logs located at: {os.path.abspath(summary_path)}")
    print(f"{'='*75}\n")


if __name__ == "__main__":
    main()