"""
finetune_mammo_SR.py
====================
Stage-2 fine-tuning of a super-resolution model for mammography images.

Starting point : a .keras model pre-trained on DIV2K (Stage 2 of TrainSR_GPU.py).
Target domain  : mammography images from the mammo-bench dataset.
Train directory: DATASET/mammo_train/  (generated by 01_select_mammo_images.py)
Val directory  : DATASET/mammo_val/

LR degradation pipeline — Med-BSR (Shao et al., IET Image Processing 2023)
combined with the 6-method MST downsampling framework:

  BLUR  : isotropic Gaussian (B_iso) or anisotropic Gaussian (B_aniso) — sampled per patch
  NOISE : additive Gaussian with 3 covariance variants (prob 2/5 · 2/5 · 1/5)
  DOWN  : one of 6 MST methods (Nearest · Bilinear · Bicubic · Lanczos · Box · Hamming)
  ORDER : the three factors are applied in a randomly shuffled order per patch
          (random select/combine strategy — 6 possible orderings × 6 MST methods = 36 paths)

  TRAIN : all parameters and ordering are fully random per patch (via tf.py_function + PIL)
  VAL   : deterministic round-robin over the 6 MST methods, fixed order blur→noise→down
          → uniform coverage of all degradation types and full reproducibility across epochs

Quick start:
  # Fine-tune a single model
  python IV_finetune_mammo_SR.py \
      --model_path outputs4x/.../stage2_p128_best.keras \
      --upscale 4 --grayscale

  # Fine-tune all NAS genes in a directory
  python IV_finetune_mammo_SR.py \
      --genes_dir outputs4x/a100_fast_bestpsnr_20260519_131528 \
      --out_dir   outputs \
      --upscale 4 --grayscale

Dependencies:
  tensorflow >= 2.13, Pillow, numpy, scipy
  mammo_degradation.py  (must be in the same directory)

"""

from __future__ import annotations

import os
import csv
import glob
import datetime
import argparse
import random
import platform
from dataclasses import dataclass
from typing import List, Optional, Tuple
import time
import timeit

import numpy as np
from PIL import Image
import tensorflow as tf

# ---------------------------------------------------------------------------
# Med-BSR degradation module (must be located in the same directory).
# Provides MammoDegradation, make_degradation_fn, MST_NAMES, N_MST.
# ---------------------------------------------------------------------------
from mammo_degradation import (
    MammoDegradation,
    make_degradation_fn,
    MST_NAMES,
    N_MST,
)

AUTOTUNE     = tf.data.AUTOTUNE
ALLOWED_EXTS = (".png", ".jpg", ".jpeg", ".bmp", ".tiff", ".tif", ".webp")


# ===========================================================================
# 0) Serialisable custom layers
#    These must be registered so that tf.keras.models.load_model() can
#    reconstruct models that were saved with these layers.
# ===========================================================================

@tf.keras.utils.register_keras_serializable(package="sr")
class PixelShuffle(tf.keras.layers.Layer):
    """
    Sub-pixel convolution (PixelShuffle) implemented via tf.nn.depth_to_space.

    Rearranges elements from the channel dimension into spatial dimensions,
    effectively upscaling the feature map by `upscale_factor`.
    Required to deserialise models saved by the original TrainSR_GPU.py script.
    """

    def __init__(self, upscale_factor: int, **kwargs):
        super().__init__(**kwargs)
        self.upscale_factor = int(upscale_factor)

    def call(self, x):
        return tf.nn.depth_to_space(x, self.upscale_factor)

    def get_config(self):
        cfg = super().get_config()
        cfg.update({"upscale_factor": self.upscale_factor})
        return cfg


# ===========================================================================
# 1) Runtime configuration
# ===========================================================================

def configure_runtime(cpu_mode: bool) -> None:
    """
    Configure GPU visibility and memory growth.

    If `cpu_mode` is True, all GPUs are hidden and TensorFlow runs on CPU only.
    Otherwise, memory growth is enabled on every visible GPU to avoid allocating
    the full VRAM upfront (prevents OOM errors when sharing the GPU).
    """
    if cpu_mode:
        tf.config.set_visible_devices([], "GPU")
        return

    gpus = tf.config.list_physical_devices("GPU")
    if gpus:
        try:
            for g in gpus:
                tf.config.experimental.set_memory_growth(g, True)
            print("[GPU] memory growth enabled")
        except Exception as exc:
            print(f"[GPU] warning: {exc}")
            print("[Runtime] WARNING: GPU requested but unavailable — falling back to CPU")


def configure_threads() -> None:
    """
    Let TensorFlow choose the optimal thread count automatically (value 0).
    Prevents over-subscription on machines with many CPU cores.
    """
    try:
        tf.config.threading.set_intra_op_parallelism_threads(0)
        tf.config.threading.set_inter_op_parallelism_threads(0)
    except Exception:
        pass


def configure_mixed_precision(cpu_mode: bool) -> None:
    """
    Enable mixed-precision training (float16 compute + float32 weights) on GPU.
    On CPU or when `cpu_mode=True`, float32 is used throughout to avoid
    numerical issues on hardware that lacks native float16 support.
    """
    try:
        from tensorflow.keras import mixed_precision
        policy = "float32" if cpu_mode else "mixed_float16"
        mixed_precision.set_global_policy(policy)
        print("[MP] policy:", mixed_precision.global_policy())
    except Exception as exc:
        print(f"[MP] warning: {exc}")


def enable_xla() -> None:
    """
    Enable XLA (Accelerated Linear Algebra) JIT compilation.
    XLA fuses TensorFlow ops into optimised kernels, reducing memory bandwidth
    and improving throughput — especially useful with the conv-heavy SR models.
    Disabled automatically on macOS (MPS / Apple Silicon compatibility).
    """
    try:
        if platform.system() != "Darwin":
            tf.config.optimizer.set_jit(True)
            print("[XLA] JIT enabled")
        else:
            tf.config.optimizer.set_jit(False)
            print("[XLA] JIT disabled on macOS (MPS backend)")
    except Exception as exc:
        print(f"[XLA] warning: {exc}")


def get_strategy_auto() -> tf.distribute.Strategy:
    """
    Return a MirroredStrategy when 2+ GPUs are detected, otherwise the default
    (single-device) strategy. MirroredStrategy synchronises gradients across
    GPUs using all-reduce, scaling batch size linearly with the number of GPUs.
    """
    if len(tf.config.list_logical_devices("GPU")) >= 2:
        return tf.distribute.MirroredStrategy()
    return tf.distribute.get_strategy()


# ===========================================================================
# 2) Data configuration dataclass
# ===========================================================================

@dataclass
class DataCfg:
    """
    Central configuration for the data pipeline.

    Attributes
    ----------
    ratio      : Upscale factor (2 or 4). Sets the LR patch size as patch_size // ratio.
    patch_size : HR patch size in pixels (both height and width).
    overlap    : Sliding-window overlap fraction used during validation (0 = no overlap).
    batch_size : Number of (LR, HR) pairs per batch.
    grayscale  : If True, images are loaded as single-channel and replicated to 3 channels.
                 Mammograms are inherently grayscale; replication lets the model architecture
                 (which expects 3-channel input) work without modification.
    """
    ratio:      int   = 4
    patch_size: int   = 128
    overlap:    float = 0.1
    batch_size: int   = 32
    grayscale:  bool  = True


# ===========================================================================
# 3) File utilities
# ===========================================================================

def _is_image_file(path: str) -> bool:
    """Return True if the file extension is a supported image format."""
    return path.lower().endswith(ALLOWED_EXTS)


def list_images(directory: str) -> List[str]:
    """Return a sorted list of absolute paths to all image files in `directory`."""
    return sorted(
        os.path.join(directory, name)
        for name in os.listdir(directory)
        if os.path.isfile(os.path.join(directory, name)) and _is_image_file(name)
    )


def get_image_hw(path: str) -> Optional[Tuple[int, int]]:
    """
    Return (height, width) for the image at `path`, or None if it cannot be read.
    Uses PIL so it works with all supported formats without loading pixel data.
    """
    try:
        w, h = Image.open(path).size
        return h, w
    except Exception:
        return None


def count_patches(h: int, w: int, patch_size: int, overlap: float) -> int:
    """
    Count how many non-overlapping (or partially overlapping) patches of size
    `patch_size × patch_size` fit in an image of height `h` and width `w`.

    The sliding-window step is: step = patch_size × (1 - overlap).
    Returns 0 if the image is smaller than one patch in either dimension.
    """
    if h < patch_size or w < patch_size:
        return 0
    step = max(1, int(patch_size * (1.0 - overlap)))
    return ((h - patch_size) // step + 1) * ((w - patch_size) // step + 1)


def compute_steps_per_epoch(directory: str, cfg: DataCfg) -> Tuple[int, int, int]:
    """
    Estimate training/validation steps per epoch for all images in `directory`.

    Returns
    -------
    steps         : Number of full batches (total_patches // batch_size).
    total_patches : Total patch count across all valid images.
    used          : Number of images that yielded at least one patch.
    """
    files = list_images(directory)
    total_patches, used = 0, 0
    for path in files:
        hw = get_image_hw(path)
        if hw is None:
            continue
        n = count_patches(hw[0], hw[1], cfg.patch_size, cfg.overlap)
        if n > 0:
            total_patches += n
            used += 1
    steps = max(1, total_patches // cfg.batch_size)
    return steps, total_patches, used


# ===========================================================================
# 4) Image decoding — TF graph and Python/PIL variants
# ===========================================================================

def _decode_mammo_tf(path: tf.Tensor, grayscale: bool) -> tf.Tensor:
    """
    Decode an image file into a float32 tensor of shape [H, W, 3] inside the
    TensorFlow graph (used in the tf.data map pipeline).

    If `grayscale=True`, the image is decoded as a single channel and then
    repeated three times along the channel axis. This preserves the grayscale
    nature of mammograms while satisfying the model's 3-channel input requirement.
    """
    raw = tf.io.read_file(path)
    if grayscale:
        img = tf.image.decode_image(raw, channels=1, expand_animations=False)
        img = tf.image.convert_image_dtype(img, tf.float32)
        img.set_shape([None, None, 1])
        img = tf.repeat(img, 3, axis=-1)   # [H, W, 1] → [H, W, 3]
    else:
        img = tf.image.decode_image(raw, channels=3, expand_animations=False)
        img = tf.image.convert_image_dtype(img, tf.float32)
        img.set_shape([None, None, 3])
    return img


def _decode_mammo_pil(path: str, grayscale: bool) -> np.ndarray:
    """
    Decode an image file into a float32 numpy array of shape [H, W, 3] using PIL.
    Used inside the Python generator for the deterministic validation dataset,
    where TF graph execution is not available.
    """
    img = Image.open(path)
    if grayscale:
        arr = np.asarray(img.convert("L"), dtype=np.float32) / 255.0
        arr = arr[:, :, np.newaxis]
        arr = np.repeat(arr, 3, axis=-1)
    else:
        arr = np.asarray(img.convert("RGB"), dtype=np.float32) / 255.0
    return arr


# ===========================================================================
# 5) Training dataset
#    Random crop → Augmentation → Full Med-BSR degradation (random per patch)
# ===========================================================================

def _stateless_augment(hr: tf.Tensor, s: tf.Tensor) -> tf.Tensor:
    """
    Apply stateless (reproducible) geometric and photometric augmentation.

    Operations applied in order:
      1. Random horizontal flip
      2. Random vertical flip
      3. Random 90° rotation (k ∈ {0, 1, 2, 3})
      4. Random brightness jitter  (±10 %)
      5. Random contrast jitter    (×[0.90, 1.10])

    Using stateless ops ensures that the same patch index always produces
    the same augmentation, making training reproducible given a fixed seed.

    Parameters
    ----------
    hr : HR patch tensor, float32 [patch_size, patch_size, 3].
    s  : 2-element int32 seed tensor derived from the global patch counter.
    """
    hr = tf.image.stateless_random_flip_left_right(hr, seed=s)
    hr = tf.image.stateless_random_flip_up_down(hr, seed=s + 1)
    k  = tf.random.stateless_uniform([], seed=s + 2, minval=0, maxval=4, dtype=tf.int32)
    hr = tf.image.rot90(hr, k=k)
    hr = tf.image.stateless_random_brightness(hr, max_delta=0.10, seed=s + 3)
    hr = tf.image.stateless_random_contrast(hr, lower=0.90, upper=1.10, seed=s + 4)
    return tf.clip_by_value(hr, 0.0, 1.0)


def make_train_dataset_randomcrop(
    directory: str, cfg: DataCfg, seed: int
) -> tf.data.Dataset:
    """
    Build the infinite training dataset with on-the-fly Med-BSR degradation.

    Pipeline steps
    --------------
    1. Shuffle image paths and repeat infinitely.
    2. Decode each image to float32 [H, W, 3].
    3. Repeat each image 12 times to increase crop diversity on the small dataset.
    4. Extract a random HR crop of shape [patch_size, patch_size, 3].
    5. Apply stateless augmentation (flips, rotation, brightness, contrast).
    6. Apply full Med-BSR degradation via tf.py_function:
         - Blur  : B_iso or B_aniso, parameters sampled uniformly per patch.
         - Noise : additive Gaussian, type sampled with probabilities 2/5·2/5·1/5.
         - Down  : MST method index = patch_counter % 6, cycling through all 6 methods.
         - Order : randomly shuffled among the three factors.
    7. Batch and prefetch.

    The global patch counter (tf.data.experimental.Counter) serves as the per-patch
    seed, so blur parameters, noise level, MST method, and augmentation are all
    deterministic given the seed argument, while still varying across patches.

    Parameters
    ----------
    directory : Path to the training image directory.
    cfg       : DataCfg instance with ratio, patch_size, overlap, batch_size, grayscale.
    seed      : Base random seed for reproducibility.
    """
    paths = list_images(directory)
    if not paths:
        raise ValueError(f"No image files found in: {directory}")

    ps    = cfg.patch_size
    r     = cfg.ratio
    lr_ps = ps // r
    gray  = cfg.grayscale

    # One degradation function per tf.data worker thread (thread-safe via py_function).
    _degrade = make_degradation_fn(scale=r, seed=seed)

    # ------------------------------------------------------------------
    # Build the tf.data pipeline
    # ------------------------------------------------------------------
    ds = tf.data.Dataset.from_tensor_slices(paths)
    ds = ds.shuffle(len(paths), seed=seed, reshuffle_each_iteration=True)
    ds = ds.repeat()
    ds = ds.map(lambda p: _decode_mammo_tf(p, gray), num_parallel_calls=AUTOTUNE)

    # Repeat each decoded image to extract multiple crops without re-reading disk.
    # With only ~480 training images, 12 crops per image gives 5 760 patches/epoch.
    repeats_per_image = 12
    ds = ds.flat_map(
        lambda img: tf.data.Dataset.from_tensors(img).repeat(repeats_per_image)
    )

    # Zip with a global counter used as a per-patch seed.
    counter = tf.data.experimental.Counter(start=seed)
    ds = tf.data.Dataset.zip((ds, counter))

    def _make_pair(img: tf.Tensor, idx: tf.Tensor):
        """
        Extract one (LR, HR) training pair from a decoded image.

        Skips the image if it is smaller than the patch size (returns zeros
        and an `ok=False` flag that the subsequent filter step removes).
        """
        h  = tf.shape(img)[0]
        w  = tf.shape(img)[1]
        ok = tf.logical_and(h >= ps, w >= ps)

        # Per-patch 2-element seed: [global_seed, patch_counter mod 2^30].
        s = tf.stack([tf.cast(seed, tf.int32), tf.cast(idx % (2 ** 30), tf.int32)])

        def _do():
            # Step 1: random crop to HR patch size.
            hr = tf.image.stateless_random_crop(img, [ps, ps, 3], seed=s)

            # Step 2: geometric and photometric augmentation.
            hr = _stateless_augment(hr, s)
            hr = tf.clip_by_value(hr, 0.0, 1.0)

            # Step 3: Med-BSR degradation via PIL (outside the TF graph).
            # The MST method cycles as idx % 6 so all 6 methods are used equally.
            method_idx = tf.cast(idx % N_MST, tf.int32)

            def _py_degrade(hr_t: tf.Tensor, midx_t: tf.Tensor) -> tf.Tensor:
                lr_np = _degrade(hr_t.numpy(), int(midx_t.numpy()))
                return lr_np.astype(np.float32)

            lr = tf.py_function(_py_degrade, [hr, method_idx], tf.float32)
            lr.set_shape([lr_ps, lr_ps, 3])
            lr = tf.clip_by_value(lr, 0.0, 1.0)
            return lr, hr

        # Fall-back zero tensors for images that are too small (filtered out below).
        lr0 = tf.zeros([lr_ps, lr_ps, 3], tf.float32)
        hr0 = tf.zeros([ps,    ps,    3], tf.float32)
        lr, hr = tf.cond(ok, _do, lambda: (lr0, hr0))
        return lr, hr, ok

    ds = ds.map(_make_pair, num_parallel_calls=AUTOTUNE)
    ds = ds.filter(lambda lr, hr, ok: ok)           # discard under-sized images
    ds = ds.map(lambda lr, hr, ok: (lr, hr), num_parallel_calls=AUTOTUNE)
    ds = ds.batch(cfg.batch_size, drop_remainder=True)
    ds = ds.prefetch(AUTOTUNE)
    return ds


# ===========================================================================
# 6) Validation dataset
#    Deterministic sliding-window extraction + Med-BSR degradation
#    Fixed order blur → noise → downsample; MST method in round-robin
# ===========================================================================

def _val_generator(paths: List[str], cfg: DataCfg, scale: int):
    """
    Python generator that yields (lr_batch, hr_batch) pairs for validation.

    Design decisions
    ----------------
    - **Sliding window**: patches are extracted with a fixed stride
      (patch_size × (1 - overlap)) so the same patches are used every epoch.
    - **Fixed degradation order** (blur → noise → downsample): ensures that
      PSNR measurements are comparable across epochs and experiments.
    - **Round-robin MST**: patch_idx % 6 cycles through all six downsampling
      methods so the validation metric reflects average model performance across
      all degradation types, not just one method.
    - **Deterministic seed per patch** (seed = patch_idx): all degradation
      parameters (sigma, kernel size, noise level) are fully reproducible.

    Yields
    ------
    (lr_batch, hr_batch) : float32 numpy arrays of shape
                           (batch_size, lr_ps, lr_ps, 3) and (batch_size, ps, ps, 3).
    """
    ps          = cfg.patch_size
    lr_ps       = ps // cfg.ratio
    step        = max(1, int(ps * (1.0 - cfg.overlap)))
    gray        = cfg.grayscale
    ORDER_FIXED = [0, 1, 2]   # 0=blur, 1=noise, 2=downsample — fixed for reproducibility

    batch_lr: List[np.ndarray] = []
    batch_hr: List[np.ndarray] = []
    patch_idx = 0

    for path in paths:
        try:
            img = _decode_mammo_pil(path, gray)
        except Exception:
            continue

        h, w = img.shape[:2]
        if h < ps or w < ps:
            continue

        for y in range(0, h - ps + 1, step):
            for x in range(0, w - ps + 1, step):
                hr = img[y:y + ps, x:x + ps, :].astype(np.float32)

                # Deterministic Med-BSR degradation: seed = patch index ensures
                # every patch gets the same degradation parameters across epochs.
                deg        = MammoDegradation(scale=scale, seed=patch_idx)
                method_idx = patch_idx % N_MST
                lr         = deg(hr, method_idx=method_idx, order=ORDER_FIXED)

                batch_lr.append(lr)
                batch_hr.append(hr)
                patch_idx += 1

                # Yield a full batch and reset accumulators.
                if len(batch_lr) == cfg.batch_size:
                    yield (
                        np.asarray(batch_lr, dtype=np.float32),
                        np.asarray(batch_hr, dtype=np.float32),
                    )
                    batch_lr, batch_hr = [], []


def make_val_dataset_deterministic(
    directory: str, cfg: DataCfg
) -> Tuple[tf.data.Dataset, int]:
    """
    Wrap the validation generator as a tf.data.Dataset.

    The dataset is bounded to `val_steps` batches (computed from the total
    number of patches in the directory) and prefetched for efficiency.

    Returns
    -------
    ds        : Bounded, prefetched tf.data.Dataset yielding (LR, HR) pairs.
    val_steps : Number of batches per validation pass.
    """
    paths = list_images(directory)
    if not paths:
        raise ValueError(f"No image files found in: {directory}")

    val_steps, _, _ = compute_steps_per_epoch(directory, cfg)
    ps    = cfg.patch_size
    lr_ps = ps // cfg.ratio
    scale = cfg.ratio

    ds = tf.data.Dataset.from_generator(
        lambda: _val_generator(paths, cfg, scale),
        output_signature=(
            tf.TensorSpec(shape=(cfg.batch_size, lr_ps, lr_ps, 3), dtype=tf.float32),
            tf.TensorSpec(shape=(cfg.batch_size, ps,    ps,    3), dtype=tf.float32),
        ),
    )
    ds = ds.take(val_steps).prefetch(AUTOTUNE)
    return ds, val_steps


# ===========================================================================
# 7) PSNR metric
# ===========================================================================

@tf.keras.utils.register_keras_serializable(package="sr")
def psnr(y_true, y_pred):
    """
    Peak Signal-to-Noise Ratio computed in float32 on the [0, 1] range.

    Registered as a Keras serialisable object so it can be saved and reloaded
    as part of the model's compiled state.
    """
    y_true = tf.cast(tf.clip_by_value(y_true, 0.0, 1.0), tf.float32)
    y_pred = tf.cast(tf.clip_by_value(y_pred, 0.0, 1.0), tf.float32)
    return tf.image.psnr(y_true, y_pred, max_val=1.0)


# ===========================================================================
# 8) Model compilation and training callbacks
# ===========================================================================

def compile_model(model, lr, wd: float = 1e-8, eps: float = 1e-7) -> None:
    """
    Compile the SR model with AdamW optimiser and MSE loss.

    A very small weight decay (1e-8) and epsilon (1e-7) are used to avoid
    numerical instability at the low learning rates typical of fine-tuning.
    steps_per_execution=50 fuses 50 gradient steps into a single XLA call,
    reducing Python overhead significantly on GPU.
    """
    opt = tf.keras.optimizers.AdamW(learning_rate=lr, weight_decay=wd, epsilon=eps)
    model.compile(
        optimizer=opt,
        loss=tf.keras.losses.MeanSquaredError(),
        metrics=[psnr],
        steps_per_execution=50,
    )


def cosine_lr_schedule(initial_lr: float, total_steps: int):
    """
    Cosine decay schedule from `initial_lr` to 0 over `total_steps` steps.

    Cosine decay tends to outperform a fixed LR for domain adaptation because
    it starts with the same learning rate (allowing quick adaptation) and
    smoothly reduces it, preventing overshooting near convergence.
    """
    return tf.keras.optimizers.schedules.CosineDecay(
        initial_learning_rate=initial_lr,
        decay_steps=total_steps,
        alpha=0.0,
    )


def make_callbacks(
    stage_dir: str,
    stage_name: str,
    es_patience: int,
    es_min_delta: float,
) -> list:
    """
    Build the standard callback set for fine-tuning.

    Callbacks
    ---------
    CSVLogger        : Appends epoch-level metrics to a CSV log file.
    ModelCheckpoint  : Saves the best model (by val_psnr) and the last checkpoint.
    ReduceLROnPlateau: Halves the LR when val_psnr stagnates for patience//4 epochs.
    EarlyStopping    : Stops training and restores best weights when val_psnr
                       fails to improve by `es_min_delta` for `es_patience` epochs.
    TerminateOnNaN   : Immediately stops training if a NaN loss is detected.
    """
    os.makedirs(stage_dir, exist_ok=True)
    return [
        tf.keras.callbacks.CSVLogger(
            os.path.join(stage_dir, f"{stage_name}_log.csv"), append=False
        ),
        tf.keras.callbacks.ModelCheckpoint(
            filepath=os.path.join(stage_dir, f"{stage_name}_best.keras"),
            monitor="val_psnr", mode="max", save_best_only=True, verbose=1,
        ),
        tf.keras.callbacks.ModelCheckpoint(
            filepath=os.path.join(stage_dir, f"{stage_name}_last.keras"),
            save_best_only=False, verbose=0,
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_psnr", mode="max",
            factor=0.5, patience=max(2, es_patience // 4),
            min_lr=1e-7, verbose=1,
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor="val_psnr", mode="max",
            patience=es_patience, min_delta=es_min_delta,
            restore_best_weights=True, verbose=1,
        ),
        tf.keras.callbacks.TerminateOnNaN(),
    ]


# ===========================================================================
# 9) NAS gene discovery
# ===========================================================================

def find_best_models(genes_dir: str) -> List[Tuple[str, str]]:
    """
    Scan a NAS output directory for saved gene models.

    Looks for Stage-2 checkpoints first (stage2_p128_best.keras); falls back
    to Stage-1 checkpoints (stage1_p64_best.keras) if Stage 2 is not found.

    Parameters
    ----------
    genes_dir : Root directory containing gene_XXX/ subdirectories.

    Returns
    -------
    List of (gene_name, model_path) tuples sorted by gene name.
    """
    pattern_st2 = os.path.join(genes_dir, "gene_*", "stage2_p128_best.keras")
    pattern_st1 = os.path.join(genes_dir, "gene_*", "stage1_p64_best.keras")
    found = sorted(glob.glob(pattern_st2)) or sorted(glob.glob(pattern_st1))
    return [(os.path.basename(os.path.dirname(p)), p) for p in found]


# ===========================================================================
# 10) Single-model fine-tuning
# ===========================================================================

def finetune_one(
    model_path: str,
    train_ds: tf.data.Dataset,
    val_ds: tf.data.Dataset,
    train_steps: int,
    val_steps: int,
    out_dir: str,
    model_name: str,
    lr: float,
    max_epochs: int,
    es_patience: int,
    es_min_delta: float,
    strategy: tf.distribute.Strategy,
    use_cosine_lr: bool,
) -> Tuple[float, str, int]:
    """
    Load a pre-trained SR model and fine-tune it on the mammography dataset.

    The model is loaded inside the distribution strategy scope so that its
    variables are placed on the correct devices from the start.

    Parameters
    ----------
    model_path    : Path to the source .keras model file.
    train_ds      : Infinite training dataset (LR, HR) pairs.
    val_ds        : Bounded validation dataset (LR, HR) pairs.
    train_steps   : Number of batches per training epoch.
    val_steps     : Number of batches per validation pass.
    out_dir       : Root output directory; a subdirectory `model_name/` is created.
    model_name    : Name used for the output subdirectory and checkpoint file names.
    lr            : Initial learning rate.
    max_epochs    : Maximum number of training epochs (EarlyStopping may stop sooner).
    es_patience   : EarlyStopping patience in epochs.
    es_min_delta  : Minimum val_psnr improvement to reset the EarlyStopping counter.
    strategy      : Distribution strategy (single-GPU or MirroredStrategy).
    use_cosine_lr : If True, use cosine decay; otherwise use fixed LR + ReduceLROnPlateau.

    Returns
    -------
    best_psnr    : Best validation PSNR achieved during training (dB).
    best_path    : Path to the saved best checkpoint (.keras file).
    param_count  : Total number of trainable parameters in the model.
    """
    print(f"\n  Loading model: {model_path}")

    with strategy.scope():
        model = tf.keras.models.load_model(model_path, compile=False)

        if use_cosine_lr:
            total_steps = max_epochs * train_steps
            compile_model(model, lr=cosine_lr_schedule(lr, total_steps))
            print(f"  LR schedule: cosine decay {lr} → 0 over {total_steps} steps")
        else:
            compile_model(model, lr=lr)
            print(f"  LR: fixed {lr}  (+ReduceLROnPlateau)")

    param_count = int(model.count_params())
    print(f"  Parameters: {param_count:,}")

    stage_dir = os.path.join(out_dir, model_name)
    os.makedirs(stage_dir, exist_ok=True)

    history = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=max_epochs,
        steps_per_epoch=train_steps,
        validation_steps=val_steps,
        callbacks=make_callbacks(stage_dir, "mammo_ft", es_patience, es_min_delta),
        verbose=1,
    )

    best_psnr = float(np.nanmax(history.history.get("val_psnr", [np.nan])))
    best_path = os.path.join(stage_dir, "mammo_ft_best.keras")
    print(f"  Best val_psnr: {best_psnr:.4f} dB  →  {best_path}")

    # Release GPU memory before the next model is loaded.
    tf.keras.backend.clear_session()
    return best_psnr, best_path, param_count


# ===========================================================================
# 11) CLI argument parsing
# ===========================================================================

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Fine-tune a super-resolution model on mammography images "
            "using Med-BSR degradation and 6-method MST downsampling."
        )
    )

    # --- Data paths ----------------------------------------------------------
    p.add_argument("--train_dir", default="DATASET/mammo_train",
                   help="Directory with training HR images.")
    p.add_argument("--val_dir",   default="DATASET/mammo_val",
                   help="Directory with validation HR images.")
    p.add_argument("--out_dir",   default="outputs",
                   help="Root output directory for checkpoints and logs.")

    # --- Model selection (mutually exclusive) --------------------------------
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--model_path", metavar="PATH",
                   help="Path to a single .keras model to fine-tune.")
    g.add_argument("--genes_dir",  metavar="DIR",
                   help="NAS output directory; all gene_XXX/ models are fine-tuned.")

    # --- Training hyperparameters --------------------------------------------
    p.add_argument("--lr",           type=float, default=1e-5,
                   help="Initial learning rate (default: 1e-5).")
    p.add_argument("--max_epochs",   type=int,   default=100,
                   help="Maximum training epochs (default: 100).")
    p.add_argument("--batch_size",   type=int,   default=32,
                   help="Batch size (default: 32).")
    p.add_argument("--patch_size",   type=int,   default=128,
                   help="HR patch size in pixels (default: 128).")
    p.add_argument("--upscale",      type=int,   default=4,
                   help="Upscale factor: 2 or 4. Affects blur sigma ranges (default: 4).")
    p.add_argument("--overlap",      type=float, default=0.1,
                   help="Sliding-window overlap for validation patches (default: 0.1).")
    p.add_argument("--es_patience",  type=int,   default=12,
                   help="EarlyStopping patience in epochs (default: 12).")
    p.add_argument("--es_min_delta", type=float, default=0.01,
                   help="Minimum val_psnr improvement to reset EarlyStopping (default: 0.01).")
    p.add_argument("--cosine_lr",    action="store_true",
                   help="Use cosine decay LR schedule instead of fixed LR + ReduceLROnPlateau.")

    # --- Image options -------------------------------------------------------
    p.add_argument("--grayscale", action="store_true",
                   help="Load images as grayscale and replicate to 3 channels.")

    # --- Runtime options -----------------------------------------------------
    p.add_argument("--cpu",    action="store_true",
                   help="Force CPU execution (for debugging on machines without a GPU).")
    p.add_argument("--seed",   type=int, default=42,
                   help="Global random seed for reproducibility (default: 42).")
    p.add_argument("--no_xla", action="store_true",
                   help="Disable XLA JIT compilation.")

    return p.parse_args()


# ===========================================================================
# 12) Entry point
# ===========================================================================

def main() -> None:
    args = parse_args()

    # --- Runtime setup -------------------------------------------------------
    configure_threads()
    configure_runtime(cpu_mode=args.cpu)
    configure_mixed_precision(cpu_mode=args.cpu)
    if not args.no_xla:
        enable_xla()

    print(f"TensorFlow : {tf.__version__}")
    print(f"CPU mode   : {args.cpu}")
    print(f"GPUs       : {len(tf.config.list_logical_devices('GPU'))}")
    print(f"Grayscale  : {args.grayscale}")
    print(f"MST ({N_MST}): {MST_NAMES}")
    print(f"Degradation: Med-BSR blur+noise+down  (scale ×{args.upscale})")

    # Global seeds — cover Python random, NumPy, and TensorFlow.
    random.seed(args.seed)
    np.random.seed(args.seed)
    tf.random.set_seed(args.seed)

    # --- Data configuration --------------------------------------------------
    cfg = DataCfg(
        ratio      = args.upscale,
        patch_size = args.patch_size,
        overlap    = args.overlap,
        batch_size = args.batch_size,
        grayscale  = args.grayscale,
    )

    print(f"\n[DATA] Building pipelines ...")
    print(f"  Train : {args.train_dir}")
    print(f"  Val   : {args.val_dir}")

    train_steps, train_patches, train_imgs = compute_steps_per_epoch(args.train_dir, cfg)
    val_steps,   val_patches,   val_imgs   = compute_steps_per_epoch(args.val_dir,   cfg)

    print(f"  Train  imgs={train_imgs}  patches={train_patches:,}  steps/epoch={train_steps:,}")
    print(f"  Val    imgs={val_imgs}    patches={val_patches:,}    steps/epoch={val_steps:,}")
    print(f"  Train degradation : Med-BSR fully random (blur+noise+down, shuffled order)")
    print(f"  Val   degradation : Med-BSR deterministic (blur→noise→down, MST round-robin)")

    train_ds          = make_train_dataset_randomcrop(args.train_dir, cfg, seed=args.seed + 11)
    val_ds, val_steps = make_val_dataset_deterministic(args.val_dir, cfg)

    # --- Output directories --------------------------------------------------
    run_id = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    root   = os.path.join(f"{args.out_dir}{args.upscale}x", f"mammo_blindSR{run_id}")
    os.makedirs(root, exist_ok=True)

    strategy = get_strategy_auto()
    print(f"[STRATEGY] {type(strategy).__name__}  replicas: {strategy.num_replicas_in_sync}")

    # --- Resolve model list --------------------------------------------------
    if args.model_path:
        models_to_run = [("model", args.model_path)]
    else:
        models_to_run = find_best_models(args.genes_dir)
        if not models_to_run:
            print(f"[ERROR] No .keras models found in: {args.genes_dir}")
            return
        print(f"\n[GENES] {len(models_to_run)} model(s) found for fine-tuning")

    # --- Summary CSV ---------------------------------------------------------
    summary_path = os.path.join(root, f"finetune_summary_{run_id}.csv")
    fieldnames   = ["model_name", "source_model", "params", "best_val_psnr", "ft_model_path", "Seconds"]
    with open(summary_path, "w", newline="", encoding="utf-8") as f:
        csv.DictWriter(f, fieldnames=fieldnames).writeheader()

    # --- Fine-tuning loop ----------------------------------------------------
    for model_name, model_path in models_to_run:
        print(f"\n{'='*60}")
        print(f"  Fine-tuning: {model_name}")
        print(f"{'='*60}")
        tic = time.perf_counter()
        best_psnr, ft_model_path, params = finetune_one(
            model_path    = model_path,
            train_ds      = train_ds,
            val_ds        = val_ds,
            train_steps   = train_steps,
            val_steps     = val_steps,
            out_dir       = root,
            model_name    = model_name,
            lr            = args.lr,
            max_epochs    = args.max_epochs,
            es_patience   = args.es_patience,
            es_min_delta  = args.es_min_delta,
            strategy      = strategy,
            use_cosine_lr = args.cosine_lr,
        )
        toc = time.perf_counter()
        # Append result row to the summary CSV.
        with open(summary_path, "a", newline="", encoding="utf-8") as f:
            csv.DictWriter(f, fieldnames=fieldnames).writerow({
                "model_name":    model_name,
                "source_model":  model_path,
                "params":        params,
                "best_val_psnr": best_psnr,
                "ft_model_path": ft_model_path,
                "Seconds":       (toc - tic)
            })

    print(f"\n{'='*60}")
    print(f"  Done. Results saved to: {root}")
    print(f"  Summary CSV: {summary_path}")
    print(f"{'='*60}\n")
    print(f"[time] Elapsed time: {toc - tic:.6f} seconds\n")

if __name__ == "__main__":
    main()
