"""
This script loads a Keras model generated by SRIR, reads low-resolution images,
processes them with the model to generate high-resolution outputs,
and saves the resulting images.
If the corresponding high-resolution ground-truth images are available,
the script also computes the PSNR and SSIM between the generated and reference
images and records the results in a CSV file.
*PSNR/SSIM are computed on the Y channel of the YCbCr color space.
The script is designed in a modular way, allowing users to easily modify model,
input, and output paths, as well as add or remove models for evaluation without
changing the core processing logic.

The script requires valid paths to:
    - the high-resolution images
    - the low-resolution images
    - the SRIR-generated models
Ensure that these paths are properly configured according to your file structure
before execution.

Updated: 2026-06-15 — PSNR computation changed to use the Y channel of YCbCr.
Updated: 2026-06-16 — SSIM added; inference-only function removed.
"""

import os
import numpy as np
import tensorflow as tf
from PIL import Image
import csv
import tifffile
import pydicom


def load_image_universal(path):
    """
    Loads an image from disk and returns a float32 array in the range [0, 1]
    with shape (H, W, 3).

    Supported formats: DICOM, TIFF/TIF (8-bit and 16-bit), PGM, PNG, JPEG, and BMP.
    """
    ext = os.path.splitext(path)[1].lower()  # Get file extension

    if ext == ".dcm":
        # DICOM: apply Rescale Slope and Rescale Intercept.
        # Note: some DICOM files may cause issues; converting them to TIFF is recommended.
        ds = pydicom.dcmread(path)
        img = ds.pixel_array.astype(np.float32)

        # Apply Rescale Slope and Intercept (if available) to obtain physical values.
        if 'RescaleIntercept' in ds and 'RescaleSlope' in ds:
            img = img * ds.RescaleSlope + ds.RescaleIntercept

        # Min-max normalization to map values to the [0, 1] range.
        img_min, img_max = img.min(), img.max()
        if img_max > img_min:
            img = (img - img_min) / (img_max - img_min)
        else:
            img = np.zeros_like(img)

    # TIFF images
    elif ext in [".tif", ".tiff"]:
        img = tifffile.imread(path)
        img = img.astype(np.float32)

        # Normalize according to the image bit depth.
        if img.dtype == np.uint16 or img.max() > 255:
            img /= 65535.0
        else:
            img /= 255.0

    # PGM images
    elif ext in [".pgm"]:
        with Image.open(path) as pil_img:
            img = np.array(pil_img).astype(np.float32)
            # Standard normalization.
            if img.max() > 255:
                img /= 65535.0
            else:
                img /= 255.0

    # Other formats (PNG, JPEG, BMP, etc.)
    else:
        img_bytes = tf.io.read_file(path)
        img = tf.image.decode_image(img_bytes, channels=3, expand_animations=False)
        img = tf.image.convert_image_dtype(img, tf.float32)
        img = img.numpy()

    # Replicate grayscale images across three channels to match the model input format.
    if img.ndim == 2:
        img = np.stack([img] * 3, axis=-1)

    return img


# ── Model reconstruction ─────────────────────────────────────────────────
# Needed in order to rebuild the model
@tf.keras.utils.register_keras_serializable(package="sr")
class PixelShuffle(tf.keras.layers.Layer):
    def __init__(self, upscale_factor: int, **kwargs):
        super().__init__(**kwargs)
        self.upscale_factor = int(upscale_factor)

    def call(self, x):
        return tf.nn.depth_to_space(x, self.upscale_factor)

    def get_config(self):
        cfg = super().get_config()
        cfg.update({"upscale_factor": self.upscale_factor})
        return cfg


@tf.keras.utils.register_keras_serializable(package="sr")
def psnr(y_true, y_pred):
    y_true = tf.cast(tf.clip_by_value(y_true, 0.0, 1.0), tf.float32)
    y_pred = tf.cast(tf.clip_by_value(y_pred, 0.0, 1.0), tf.float32)
    return tf.image.psnr(y_true, y_pred, max_val=1.0)


# ── RGB → Y channel conversion (BT.601, standard for SR benchmarks) ────────
def rgb_to_y(img_np: np.ndarray) -> np.ndarray:
    """Converts a float32 RGB image [0,1] to the Y channel of YCbCr [0,1].
    Follows the BT.601 convention used by standard SR benchmarks (EDSR, SRCNN, etc.).
    Formula (values on a [0,255] scale):
        Y = 16 + 65.481*R + 128.553*G + 24.966*B
    which maps to [16/255, 235/255] ~= [0.0627, 0.9216] in [0,1] space.
    """
    r, g, b = img_np[..., 0], img_np[..., 1], img_np[..., 2]
    y = 16.0 / 255.0 + (65.481 * r + 128.553 * g + 24.966 * b) / 255.0
    return y.astype(np.float32)


# ── Super-resolution + PSNR + SSIM ─────────────────────────────────────────
def run_super_resolution_and_psnr(
    model_path: str,
    low_res_path: str,
    ground_truth_path: str,
    output_image_path: str,
    scale_factor: int = 2,
    csv_path: str = "registro_psnr.csv"
) -> None:
    """
    Loads a super-resolution model, generates SR images, and computes PSNR and SSIM
    on the Y channel of the YCbCr color space, following the standard evaluation
    protocol used in super-resolution benchmarks. Results are saved to a CSV file.

    Output CSV structure:
    Filename, PSNR (dB), SSIM

    Parameters
    ----------
    model_path         : Path to the .keras model file.
    low_res_path       : Directory containing the input LR images.
    ground_truth_path  : Directory containing the HR ground-truth images.
    output_image_path  : Directory where the generated SR images will be saved.
    scale_factor       : Upscaling factor (e.g. 2 or 4); used as the border-cropping margin.
    csv_path            : Path to the output CSV file.
    """
    # 1. Load the model
    print(f"Loading model from: {model_path}...")
    model = tf.keras.models.load_model(
        model_path,
        custom_objects={"PixelShuffle": PixelShuffle, "psnr": psnr}
    )

    # 2. Prepare output directory
    if not os.path.exists(output_image_path):
        os.makedirs(output_image_path)

    psnr_list = []
    ssim_list = []
    results = {}  # dict { filename: (psnr_val, ssim_val) }

    for filename in sorted(os.listdir(low_res_path)):
        lr_path = os.path.join(low_res_path, filename)
        gt_path = os.path.join(ground_truth_path, filename)

        if not os.path.isfile(gt_path):
            print(f"  [SKIP] No ground truth for {filename}")
            continue
        try:
            # ---- Low-resolution image ----
            img_lr = load_image_universal(lr_path)
            input_tensor = np.expand_dims(img_lr, axis=0)

            # ── Inference ────────────────────────────────────────────────
            print(f"Processing {filename}...")
            output = np.squeeze(model.predict(input_tensor, verbose=0), axis=0)
            output = np.clip(output, 0, 1)

            # ── Save SR image ───────────────────────────────────────────
            ext = os.path.splitext(filename)[1].lower()
            if ext in [".tif", ".tiff", ".dcm"]:
                result_img = (output * 65535.0).clip(0, 65535).astype(np.uint16)
                tifffile.imwrite(os.path.join(output_image_path, filename), result_img)
            else:
                result_img = (output * 255.0).clip(0, 255).astype(np.uint8)
                Image.fromarray(result_img).save(os.path.join(output_image_path, filename))

            # ── Load ground truth ───────────────────────────────────────
            high_res = load_image_universal(gt_path)

            if high_res.shape != output.shape:
                print(f"  [WARN] Size mismatch for {filename} "
                      f"(GT {high_res.shape} vs SR {output.shape}), skipping metrics")
                continue

            # ── Crop image according to scale ───────────────────────────
            margin = scale_factor  # e.g. scale=2 -> 2px margin
            if margin > 0:
                high_res_crop = high_res[margin:-margin, margin:-margin, :]
                output_crop = output[margin:-margin, margin:-margin, :]
            else:
                high_res_crop = high_res
                output_crop = output

            # ---- Y channel extraction ──────────────────────────────────
            y_true_y = rgb_to_y(high_res_crop)  # shape (H, W)
            y_pred_y = rgb_to_y(output_crop)    # shape (H, W)

            # tf.image.psnr expects tensors with at least 3 dims -> (1, H, W, 1)
            y_true_t = tf.expand_dims(tf.expand_dims(y_true_y, axis=0), axis=-1)
            y_pred_t = tf.expand_dims(tf.expand_dims(y_pred_y, axis=0), axis=-1)
            psnr_val = tf.image.psnr(y_true_t, y_pred_t, max_val=1.0).numpy()[0]
            ssim_val = tf.image.ssim(y_true_t, y_pred_t, max_val=1.0).numpy()[0]

            psnr_list.append(psnr_val)
            ssim_list.append(ssim_val)
            results[filename] = (psnr_val, ssim_val)
            print(f"  PSNR: {psnr_val:.4f} dB  |  SSIM: {ssim_val:.4f}")

        except tf.errors.InvalidArgumentError:
            print(f"  [ERROR] InvalidArgumentError for {filename}, file skipped")
            continue

    # ── Summary ────────────────────────────────────────────────────────────
    if psnr_list:
        print(f"\nAverage PSNR : {np.mean(psnr_list):.4f} dB")
        print(f"Average SSIM : {np.mean(ssim_list):.4f}")

    # ── Save / update CSV ────────────────────────────────────────────────
    csv_file = os.path.join(output_image_path, csv_path)

    if os.path.isfile(csv_file):
        # Read existing CSV and update rows
        with open(csv_file, 'r', newline='', encoding='utf-8') as f:
            rows = list(csv.reader(f))

        for row in rows:
            if not row:
                continue
            key = row[0]
            if key in results:
                psnr_v, ssim_v = results[key]
                # Update or append PSNR and SSIM columns (indices 1 and 2)
                while len(row) < 3:
                    row.append("")
                row[1] = f"{psnr_v:.4f}"
                row[2] = f"{ssim_v:.4f}"

        with open(csv_file, 'w', newline='', encoding='utf-8') as f:
            csv.writer(f).writerows(rows)
    else:
        with open(csv_file, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['Filename', 'PSNR (dB)', 'SSIM'])
            for filename, (psnr_v, ssim_v) in results.items():
                writer.writerow([filename, f"{psnr_v:.4f}", f"{ssim_v:.4f}"])

    print(f"Results saved to: {csv_file}")


# ── Example usage ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    model_file = "outputs/gene_001/stage1_p64_best.keras"
    input_dir = "randomtest/"
    output_dir = "out/"

    if os.path.exists(model_file):
        run_super_resolution_and_psnr(model_file, input_dir, output_dir)
    else:
        print("Error: model file not found.")
